### ISSUE TITLE
Small UX improvements

### ISSUE THREAD

**Issue by schneiderfelipe** [Clonkk/nimjl#28]
Hi @Clonkk, as I said, I think this is a great project ✨. But I believe `nimpy` has a better user experience currently, though:

```nim
import nimpy

let np = pyImport("numpy")

# An attempt to translate the README example to nimpy
var myval = 4.0
var res = np.sqrt(myval)
echo res
```

```bash
❯ nim c -r -d:danger --opt:speed --verbosity=0 asdf.nim
..............................2.0
```

No
a. `init` or `exit`
b. no default imports (faster/more straightforward/more explicit interface?)
c. no typecasting

So I have two questions and a suggestion:

1. I know the following works because I've tested:

```nim
import nimjl

Julia.init()

var myval = 4.0              # no `'f64`
var res = Julia.sqrt(myval)  # no `to(float)`
echo res

Julia.exit()
```

So, do we need type conversions? Can't Julia types (primitives at least) be mapped automatically to Nim types/primitives? Isn't it done already? (I haven't looked at the code yet.)

2. I know `sqrt` comes from the Julia `Base` module ([from the docs about embedding](https://docs.julialang.org/en/v1/manual/embedding/#Calling-Julia-Functions) and [here](https://docs.julialang.org/en/v1/base/math/#Base.sqrt-Tuple{Real})). What's behind the design decision of not making it explicit in Nim? For instance, `nimpy` requires importing a [builtin module](https://github.com/yglukhov/nimpy#calling-python-from-nim):

```nim
import nimpy

let py = pyBuiltinsModule()
```

(As a second thought, I'm not sure how to import a Julia module yet, so that this comment might be just too naive/simply dumb.)

3. Embedding Julia in C requires `init` and `exit`, okay. But should this be mapped to Nim? `init` can be called as soon as `nimjl` is imported, so problem solved. The tricky part is to call `exit`, so I tried a couple of ways of deferring this to the end of the program. Here's what I've found:

**`defer` does not work** (I didn't know that):

```nim
...
defer:
  Julia.exit()
# =>
# Error: defer statement not supported at top level
```

**Using `std/exitprocs` work** 🎉:

```nim
import nimjl
import std/exitprocs

Julia.init()
addExitProc proc =
  echo "Cleaning up nimjl!"
  Julia.exit()


# Actual working code:
var myval = 4.0
var res = Julia.sqrt(myval)
echo res
echo "That's all folks!"
```

```nim
$ nim c -r -d:danger --opt:speed --verbosity=0 exitprocstest.nim
................................................................................................................................................................................................................................................
Nimjl> Using Julia install: /opt/julias/julia-1.6.0
..2.0
That's all folks!
Cleaning up nimjl!
```

(Even though I like the solution above, another possibility would be to have a top-level, global object that runs `Julia.exit` in its destructor, but I haven't tested that, and I'm not sure if it has any extra advantage over the above.)

**Comment by Clonkk** [comment]
> b. no default imports (faster/more straightforward/more explicit interface?)

Defaults import are part of Julia's VM and it's not something I can easily change. 

> So, do we need type conversions? Can't Julia types (primitives at least) be mapped automatically to Nim types/primitives? Isn't it done already? (I haven't looked at the code yet.)

Nimpy does not map type directly, neither does Nimjl. In both library, you don't need to convert the Julia value to Nim value to handle it. 
The conversion is needed if you then want to use the value in a ``proc`` that takes a float as signature for example. It was just a simple example to show how converting value works but It's not required.

Here's a piece of code that show case this  : 
```nim
import nimpy

block:
  let np = pyImport("numpy")
# An attempt to translate the README example to nimpy
  var myval = 4.0
  var res = np.sqrt(myval) 
  echo res # 4.0
  echo typeof(res) # PyObject
  var nres = res.to(float64)
  echo nres # float64
  echo typeof(nres) # 4.0

import nimjl
Julia.init()
block:
  var res = Julia.sqrt(4.0) + Julia.sqrt(4.0)
  echo res # 4.0
  echo typeof(res) # JlValue
  var nres = res.to(float64)
  echo nres # 4.0
  echo typeof(nres) # float64
```

> I know sqrt comes from the Julia Base module (from the docs about embedding and here). What's behind the design decision of not making it explicit in Nim? For instance, nimpy requires importing a builtin module:

Calling ``Julia.myfunc`` is identical to calling ``JlMain.myfunc``. I just found it easier to remember and since in most case,  ``JlMain`` is what you want it, it's just simpler. 
You can explicitly call a function with the dot syntax and a Julia module, either one of the pre-existing one such as ``JlMain``, ``JlBase``, ``JlCore``, ``JlTop`` (but to be honest I've only ever used ``JlBase`` and ``JlMain``) or with an imported module : 

```nim
import nimjl
Julia.init()
var mymod = jlGetModule("customModule") # Make sure the module is available in Julia
mymod.myfunc()
Julia.exit()
```

>  Embedding Julia in C requires init and exit, okay. But should this be mapped to Nim? init can be called as soon as nimjl is imported, so problem solved. The tricky part is to call exit, so I tried a couple of ways of deferring this to the end of the program. Here's what I've found:

Regarding init, I made it explicit because later i'd like to support initalizing Julia VM with a pre-existing image (pre-compiled Julia code basically) and that would be difficult if the init cannot be controlled by the user. I'd have to introducing compile-time switch to handle differently the case.

That's an increase in complexity and stuff to remember and document for the user just to avoid a one-liner, I'm not sure it's worth it. 

I didn't know about ``std/exitprocs`` that's a neat trick; I'd like to keep a possible early exit before the end of the process but the exit could be made optional with your solution.

Personally, having to call ``init`` / ``exit`` manually doesn't bother me so I didn't put that much thought into avoiding it but I'm not against the idea, 

> defer does not work (I didn't know that):

Defer does not work in global scope ;)


> (Even though I like the solution above, another possibility would be to have a top-level, global object that runs Julia.exit in its destructor, but I haven't tested that, and I'm not sure if it has any extra advantage over the above.)

Destructor are ignored if you don't use ``gc:arc/orc``. Also, it's unnecessary complicated.

**Comment by schneiderfelipe** [comment]
Great I think I got all your points, everything makes perfect sense. Being able to initialize a pre-existing image is indisputably useful. Thank you for taking the time to answer so thoroughly. 

> I didn't know about `std/exitprocs` that's a neat trick; I'd like to keep a possible early exit before the end of the process but the exit could be made optional with your solution.

Just out of curiosity, could you point out a use case for exiting early?

**Comment by Clonkk** [comment]
> Just out of curiosity, could you point out a use case for exiting early?

The only benefit of exiting early is freeing the memory used by the Julia VM. So if you're a platform with limited RAM that can be handy to free Julia VM completly but that's very limited.

In practice I think most users will just exit the VM at the end of the process so ``std/exitprocs`` makes sense. 

I might end up adding a small state machine for the init / exit handling, but I'll think about it a bit more so I don't end-up adding more complexity to solve non-problem.

**Comment by Clonkk** [comment]
I'll close this with #29 . Auto calling exit was a good idea; I'll just keep explicit init for now because I plan on adding image loading once I figure out how it works.
